# Generated by Django 4.1.3 on 2022-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_description_alter_item_name_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
